# Generated by Django 5.2 on 2025-06-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='monitored_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_monitor.monitoredapi'),
        ),
    ]
