# Generated by Django 5.2 on 2025-06-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitor', '0003_remove_apikey_last_used_at_remove_apikey_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimetric',
            name='api',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='monitored_api',
        ),
        migrations.AddField(
            model_name='apimetric',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='apimetric',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MonitoredAPI',
        ),
    ]
